Roal\JewelryBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: Roal\JewelryBundle\Entity\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        categoryId:
            type: integer
            column: category_id
        userId:
            type: integer
            column: user_id
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
        notice:
            type: string
            length: 255
        creationTs:
            type: datetime
            column: creation_ts
        changeTs:
            type: datetime
            column: change_ts
    lifecycleCallbacks: {  }
