app_job:
    pattern:  /
    defaults: { _controller: "AppJoboardBundle:Job:index" }

app_job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "AppJoboardBundle:Job:show" }
    requirements:
        id:  \d+

app_job_new:
    pattern:  /new
    defaults: { _controller: "AppJoboardBundle:Job:new" }

app_job_create:
    pattern:  /create
    defaults: { _controller: "AppJoboardBundle:Job:create" }
    requirements: { _method: post }

app_job_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AppJoboardBundle:Job:edit" }

app_job_update:
    pattern:  /{id}/update
    defaults: { _controller: "AppJoboardBundle:Job:update" }
    requirements: { _method: post|put }

app_job_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AppJoboardBundle:Job:delete" }
    requirements: { _method: post|delete }