app_job:
    path:     /
    defaults: { _controller: "AppJoboardBundle:Job:index" }

app_job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "AppJoboardBundle:Job:show" }
    requirements:
        id:  \d+

app_job_new:
    path:     /new
    defaults: { _controller: "AppJoboardBundle:Job:new" }

app_job_create:
    path:     /create
    defaults: { _controller: "AppJoboardBundle:Job:create" }
    methods:  POST

app_job_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppJoboardBundle:Job:edit" }

app_job_update:
    path:     /{id}/update
    defaults: { _controller: "AppJoboardBundle:Job:update" }
    methods:  [POST, PUT]

app_job_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppJoboardBundle:Job:delete" }
    methods:  [POST, DELETE]
